// src/constants/enemies.js
// Enemy type definitions — includes flat DEF, percentage RES, and Ranged Caster

export const ENEMY_DATA = {
  basic: {
    id: 'basic',
    name: 'Basic',
    color: '#E74C3C',
    glowColor: 'rgba(231,76,60,0.5)',
    shape: 'circle',
    baseHp: 250,
    baseSpeed: 1.0,
    reward: 10,
    damage: 5,
    def: 0,
    res: 0.0,
    isBoss: false,
    isAerial: false,
    immuneSlow: false,
    spawnCount: 1,
    size: 14,
  },
  fast: {
    id: 'fast',
    name: 'Fast',
    color: '#F39C12',
    glowColor: 'rgba(243,156,18,0.5)',
    shape: 'triangle',
    baseHp: 50,
    baseSpeed: 2.1,
    reward: 15,
    damage: 25,
    def: 5,
    res: 0.0,
    isBoss: false,
    isAerial: false,
    immuneSlow: false,
    spawnCount: 1,
    size: 12,
  },
  armored: {
    id: 'armored',
    name: 'Armored',
    color: '#7F8C8D',
    glowColor: 'rgba(127,140,141,0.5)',
    shape: 'square',
    baseHp: 600,
    baseSpeed: 0.7,
    reward: 25,
    damage: 20,
    def: 75,            // High flat defense - Sniper's nightmare!
    res: 0.1,           // Low resistance - Caster's playground!
    isBoss: false,
    isAerial: false,
    immuneSlow: false,
    spawnCount: 1,
    size: 16,
  },
  boss: {
    id: 'boss',
    name: 'BOSS',
    color: '#8E44AD',
    glowColor: 'rgba(142,68,173,0.7)',
    shape: 'hexagon',
    baseHp: 1200,
    baseSpeed: 0.5,
    reward: 100,
    damage: 200,
    def: 100,
    res: 0.3,
    isBoss: true,
    isAerial: false,
    immuneSlow: false,
    spawnCount: 1,
    size: 22,
  },
  swarm: {
    id: 'swarm',
    name: 'Swarm',
    color: '#27AE60',
    glowColor: 'rgba(39,174,96,0.5)',
    shape: 'diamond',
    baseHp: 30,
    baseSpeed: 1.1,
    reward: 5,
    damage: 20,
    def: 2,
    res: 0.0,
    isBoss: false,
    isAerial: false,
    immuneSlow: false,
    spawnCount: 6,
    size: 10,
  },
  drone: {
    id: 'drone',
    name: 'Drone',
    color: '#00D4FF',
    glowColor: 'rgba(0,212,255,0.6)',
    shape: 'drone',
    baseHp: 70,
    baseSpeed: 1.6,
    reward: 18,
    damage: 1,
    def: 10,
    res: 0.15,
    isBoss: false,
    isAerial: true,
    immuneSlow: false,
    spawnCount: 1,
    size: 13,
  },
  // ─── NEW: Ranged Enemy — attacks placed defense units from a distance ─────
  ranged: {
    id: 'ranged',
    name: 'Ranged',
    color: '#E67E22',
    glowColor: 'rgba(230,126,34,0.5)',
    shape: 'pentagon',
    baseHp: 250,
    baseSpeed: 0.9,
    reward: 20,
    damage: 50,
    def: 15,
    res: 0.1,
    isBoss: false,
    isAerial: false,
    immuneSlow: false,
    spawnCount: 1,
    size: 13,
    range: 2,           // Chebyshev cells range
    attackInterval: 1.5,
  },
};

// Compute scaled enemy stats based on wave and difficulty modifier
export function getEnemyStats(type, wave, difficultyMod = 1.0) {
  const base = ENEMY_DATA[type];
  const waveScale = 1 + (wave - 1) * 0.08; // +8% per wave
  return {
    ...base,
    hp: Math.round(base.baseHp * waveScale * difficultyMod),
    maxHp: Math.round(base.baseHp * waveScale * difficultyMod),
    speed: base.baseSpeed * (type === 'swarm' ? Math.min(1 + (wave - 1) * 0.005, 1.1) : Math.min(1 + (wave - 1) * 0.02, 1.5)),
    def: Math.round((base.def || 0) * (1 + (wave - 1) * 0.05)),
  };
}
